# Generated by Django 6.0.2 on 2026-06-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('reception', 'Reception'), ('waiter', 'Waiter'), ('cashier', 'Cashier'), ('kitchen', 'Kitchen'), ('bar', 'Bar'), ('inventory', 'Inventory'), ('delivery', 'Delivery'), ('finance', 'Finance'), ('customer', 'Customer')], default='waiter', max_length=20),
        ),
    ]
