# Generated by Django 6.0.2 on 2026-07-23 22:04

import core.storage
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_options_user_unique_user_email_ci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=core.storage.secure_profile_pic_path, validators=[core.validators.validate_file_signature, core.validators.validate_upload_size]),
        ),
    ]
