# Generated by Django 6.0.3 on 2026-04-26 17:05

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=200, verbose_name='Hotel Name')),
                ('enabled_features', models.JSONField(blank=True, default=list, help_text='List of active package codes for this hotel. Example: ["pos", "inventory", "kitchen_display"]')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hotel_logos/')),
                ('is_active', models.BooleanField(default=True, help_text='Suspend a hotel without deleting data.')),
                ('subscription_plan', models.CharField(default='starter', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hotel (Tenant)',
                'verbose_name_plural': 'Hotels (Tenants)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.SlugField(choices=[('pos', 'Point of Sale (POS)'), ('inventory', 'Inventory Management'), ('finance', 'Finance & Accounting'), ('kitchen_display', 'Kitchen Display System'), ('bar', 'Bar Management'), ('reservation', 'Room Reservations'), ('housekeeping', 'Housekeeping'), ('laundry', 'Laundry Service'), ('spa', 'Spa & Wellness'), ('gym', 'Gym & Fitness'), ('parking', 'Parking Management'), ('room_service', 'Room Service'), ('delivery', 'Delivery Management'), ('crm', 'CRM & Guest Relations'), ('loyalty', 'Loyalty Programme'), ('payroll', 'Payroll & HR'), ('procurement', 'Procurement & Purchasing'), ('reporting', 'Advanced Reporting'), ('multi_branch', 'Multi-Branch Management'), ('guest_portal', 'Guest Self-Service Portal')], unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this package is available for sale on the platform.')),
            ],
            options={
                'verbose_name': 'Package / Module',
                'verbose_name_plural': 'Packages / Modules',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.hotel')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
            },
        ),
    ]
