# Generated by Django 6.0.3 on 2026-04-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='code',
            field=models.SlugField(choices=[('dashboard', 'Dashboard & Overview'), ('orders', 'Order Management'), ('payments', 'Payment Handling'), ('food_beverage', 'Food and Beverage (Menus, Categories, Tables)'), ('rooms', 'Room Management (Rooms, Bookings, Check-ins)'), ('analytics', 'Analytics & Reporting'), ('users', 'User Management'), ('settings', 'System Settings')], unique=True),
        ),
    ]
