# Generated by Django 6.0.3 on 2026-04-26 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('station', models.CharField(choices=[('Kitchen', 'Kitchen'), ('Bar', 'Bar')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_ref', models.IntegerField(help_text='ID of the recipient (users.User)')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiter_id_ref', models.IntegerField(blank=True, help_text='ID of the waiter (users.User)', null=True)),
                ('cashier_id_ref', models.IntegerField(blank=True, help_text='ID of the cashier (users.User)', null=True)),
                ('waiter_username', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('served', 'Served'), ('bill_requested', 'Bill Requested'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_charge_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Chapa', 'Chapa')], max_length=50, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('tip_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_page_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('chapa_tx_ref', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('chapa_checkout_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_code', models.CharField(max_length=20, unique=True)),
                ('label_name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=4)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('room_type', models.CharField(max_length=50)),
                ('floor_number', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weekend_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('holiday_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percent', models.IntegerField(default=0)),
                ('extra_bed_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_adults', models.IntegerField(default=2)),
                ('max_children', models.IntegerField(default=1)),
                ('bed_type', models.CharField(default='King', max_length=50)),
                ('num_beds', models.IntegerField(default=1)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='rooms/main/')),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('view_360_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Cleaning', 'Cleaning'), ('Maintenance', 'Maintenance'), ('Reserved', 'Reserved')], default='Available', max_length=20)),
                ('instant_booking', models.BooleanField(default=True)),
                ('min_stay', models.IntegerField(default=1)),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
                ('check_in_time', models.TimeField(default='14:00')),
                ('check_out_time', models.TimeField(default='11:00')),
                ('cancellation_policy', models.TextField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(default='ATLAS INTERNATIONAL HOTEL PLC', max_length=255)),
                ('tin_number', models.CharField(default='0002915740', max_length=15, verbose_name='TIN Number')),
                ('address', models.TextField(default='Bole Sub-City, Woreda 03, H.No 033')),
                ('phone_number', models.CharField(default='0116187432', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('vat_enabled', models.BooleanField(default=True)),
                ('vat_percentage', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('service_charge_enabled', models.BooleanField(default=True)),
                ('service_charge_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('fiscal_machine_no', models.CharField(default='FG10004841', max_length=50)),
                ('reading_number', models.CharField(default='0107', max_length=20)),
                ('erca_label', models.CharField(default='ERCA', max_length=20)),
                ('currency_symbol', models.CharField(default='ETB', max_length=10)),
                ('pos_machine_type', models.CharField(choices=[('none', 'No POS Machine'), ('thermal', 'Generic Thermal Printer (Raw)'), ('fiscal', 'Fiscal Printer (API/Serial)')], default='thermal', max_length=50)),
                ('pos_device_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hotel.category')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=10)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hotel.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='hotel.restauranttable'),
        ),
    ]
