# Generated by Django 6.0.3 on 2026-04-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='enabled_features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
