# Generated by Django 6.0.3 on 2026-04-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='public_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='qr_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
