# Generated by Django 6.0.2 on 2026-04-27 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_reservation_confirmation_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateField(unique=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.CharField(blank=True, max_length=150)),
                ('total_cash', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_chapa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_telebirr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_card', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_room_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-audit_date'],
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Chapa', 'Chapa'), ('Telebirr', 'Telebirr'), ('Card', 'Card')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='FolioCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('added_by', models.CharField(blank=True, max_length=150)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folio_charges', to='hotel.reservation')),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('id_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('other', 'Other')], default='national_id', max_length=30)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('id_scan', models.ImageField(blank=True, null=True, upload_to='guest_ids/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_profile', to='hotel.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reported_by', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='hotel.room')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('checkin', 'Check-In'), ('checkout', 'Check-Out'), ('maintenance', 'Maintenance'), ('cleaning', 'Cleaning')], max_length=20)),
                ('guest_name', models.CharField(blank=True, max_length=200)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='hotel.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
