# Generated by Django 6.0.2 on 2026-04-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_pms_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/extra/'),
        ),
        migrations.AddField(
            model_name='room',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/extra/'),
        ),
    ]
