# Generated by Django 6.0.2 on 2026-04-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_room_image_2_room_image_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='printer_paper_size',
            field=models.CharField(choices=[('58mm', '58mm'), ('80mm', '80mm')], default='80mm', max_length=10),
        ),
    ]
