# Generated by Django 6.0.3 on 2026-05-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_systemsettings_printer_paper_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomhistory',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
