# Generated by Django 6.0.2 on 2026-05-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_inventorycategory_supplier_inventoryitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplied_categories',
            field=models.ManyToManyField(blank=True, related_name='suppliers', to='hotel.inventorycategory', verbose_name='Supplied Ingredient Categories'),
        ),
    ]
