# Generated by Django 6.0.2 on 2026-05-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_supplier_supplied_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supply_items',
            field=models.TextField(blank=True, help_text='Comma-separated list of specific items this supplier provides', null=True, verbose_name='Specific Items Supplied'),
        ),
    ]
