# Generated by Django 6.0.2 on 2026-06-01 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_supplier_supply_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='foliocharge',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folio_charges', to='hotel.inventoryitem'),
        ),
        migrations.AddField(
            model_name='foliocharge',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventorycategory',
            name='category_type',
            field=models.CharField(choices=[('f_and_b', 'Food & Beverage'), ('housekeeping', 'Housekeeping & Rooms')], default='f_and_b', max_length=20),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='destination_dept',
            field=models.CharField(blank=True, help_text='e.g., Housekeeping, Kitchen, Bar', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='destination_room',
            field=models.CharField(blank=True, help_text='e.g., Room 104', max_length=20, null=True),
        ),
    ]
