# Generated by Django 6.0.2 on 2026-06-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_foliocharge_inventory_item_foliocharge_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price charged to guests (e.g. minibar / room service items)', max_digits=10),
        ),
    ]
