# Generated by Django 6.0.2 on 2026-06-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_account_journalentry_expensetransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(choices=[('reception', 'Reception / Front Office'), ('kitchen', 'Kitchen'), ('bar', 'Bar'), ('housekeeping', 'Housekeeping'), ('maintenance', 'Maintenance'), ('accounts', 'Accounts & Finance'), ('management', 'Management'), ('security', 'Security'), ('waiter', 'Waiter / Service Staff'), ('other', 'Other')], default='other', max_length=50)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('income_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pension_employee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pension_employer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Payroll Entries',
                'ordering': ['-pay_period_end', 'employee_name'],
            },
        ),
    ]
