# Generated by Django 6.0.2 on 2026-06-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_account_cached_balance'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['year', 'month'], name='budget_ym_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['station'], name='cat_station_idx'),
        ),
        migrations.AddIndex(
            model_name='dayauditlog',
            index=models.Index(fields=['audit_date', 'is_closed'], name='audit_date_closed_idx'),
        ),
        migrations.AddIndex(
            model_name='expensetransaction',
            index=models.Index(fields=['date'], name='exp_date_idx'),
        ),
        migrations.AddIndex(
            model_name='expensetransaction',
            index=models.Index(fields=['expense_account'], name='exp_account_idx'),
        ),
        migrations.AddIndex(
            model_name='expensetransaction',
            index=models.Index(fields=['supplier'], name='exp_supplier_idx'),
        ),
        migrations.AddIndex(
            model_name='foliocharge',
            index=models.Index(fields=['reservation'], name='folio_res_idx'),
        ),
        migrations.AddIndex(
            model_name='guestprofile',
            index=models.Index(fields=['full_name'], name='guest_name_idx'),
        ),
        migrations.AddIndex(
            model_name='guestprofile',
            index=models.Index(fields=['phone'], name='guest_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['date'], name='je_date_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryitem',
            index=models.Index(fields=['account'], name='jei_account_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryitem',
            index=models.Index(fields=['entry'], name='jei_entry_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenancelog',
            index=models.Index(fields=['room', 'status'], name='maint_room_status_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['category', 'is_available'], name='mi_cat_avail_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user_id_ref', 'is_read'], name='notif_user_read_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['table', 'status'], name='ord_table_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status'], name='ord_pay_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'payment_status'], name='ord_status_pay_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='ord_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['waiter_id_ref'], name='ord_waiter_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollentry',
            index=models.Index(fields=['pay_period_start', 'pay_period_end'], name='pay_period_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollentry',
            index=models.Index(fields=['department'], name='pay_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollentry',
            index=models.Index(fields=['status'], name='pay_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='res_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['check_in_date', 'check_out_date'], name='res_dates_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['room', 'status'], name='res_room_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['created_at'], name='res_created_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['payment_status'], name='res_pay_status_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status'], name='room_status_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['is_available_online', 'status'], name='room_online_status_idx'),
        ),
        migrations.AddIndex(
            model_name='roomhistory',
            index=models.Index(fields=['room', 'created_at'], name='rhist_room_date_idx'),
        ),
        migrations.AddIndex(
            model_name='roomhistory',
            index=models.Index(fields=['event_type'], name='rhist_event_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['item', 'transaction_type'], name='stx_item_type_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['transaction_type', 'timestamp'], name='stx_type_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['supplier'], name='stx_supplier_idx'),
        ),
    ]
