# Generated by Django 6.0.2 on 2026-07-20 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_add_database_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='chapa', max_length=30)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='ETB', max_length=3)),
                ('provider_tx_ref', models.CharField(max_length=120, unique=True)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('created', 'Created'), ('initiated', 'Initiated'), ('verified', 'Verified'), ('failed', 'Failed')], default='created', max_length=20)),
                ('provider_event_ref', models.CharField(blank=True, max_length=160, null=True, unique=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('safe_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('check_out_date__gt', models.F('check_in_date'))), name='reservation_checkout_after_checkin'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('adults__gte', 1)), name='reservation_adults_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('children__gte', 0)), name='reservation_children_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='reservation_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_amount__gte', 0)), name='reservation_deposit_nonnegative'),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='hotel.order'),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='hotel.reservation'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['provider', 'status'], name='payattempt_provider_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order__isnull', False), ('reservation__isnull', True)), models.Q(('order__isnull', True), ('reservation__isnull', False)), _connector='OR'), name='payment_attempt_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('expected_amount__gte', 0)), name='payment_attempt_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(fields=('provider', 'idempotency_key'), name='unique_provider_idempotency_key'),
        ),
    ]
