# Generated by Django 6.0.2 on 2026-07-20 20:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_inventoryitem_inventory_stock_nonnegative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='hotel.journalentry'),
        ),
        migrations.AddConstraint(
            model_name='journalentryitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount_debit__gte', 0)), name='journal_item_debit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='journalentryitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount_credit__gte', 0)), name='journal_item_credit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='journalentryitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount_debit__gt', 0), ('amount_credit__gt', 0), _connector='OR'), name='journal_item_has_amount'),
        ),
    ]
