# Generated by Django 6.0.3 on 2026-07-20 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_journalentry_posted_at_journalentry_reversal_of_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='financials_finalized_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='service_charge_rate_snapshot',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_rate_snapshot',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='hotel.stocktransaction'),
        ),
        migrations.AddConstraint(
            model_name='stocktransaction',
            constraint=models.CheckConstraint(condition=models.Q(('reversal_of__isnull', True), ('transaction_type', 'adjustment'), _connector='OR'), name='stock_reversal_must_be_adjustment'),
        ),
    ]
