# Generated by Django 6.0.3 on 2026-07-20 21:51

from decimal import Decimal

from django.db import migrations, models


def establish_opening_stock(apps, schema_editor):
    InventoryItem = apps.get_model("hotel", "InventoryItem")
    StockTransaction = apps.get_model("hotel", "StockTransaction")
    for item in InventoryItem.objects.all().iterator():
        net = Decimal("0")
        for entry in StockTransaction.objects.filter(item_id=item.pk).order_by("timestamp", "pk"):
            if entry.reversal_of_id:
                original = StockTransaction.objects.get(pk=entry.reversal_of_id)
                delta = -entry.quantity if original.transaction_type in ("purchase", "adjustment") else entry.quantity
            else:
                delta = entry.quantity if entry.transaction_type in ("purchase", "adjustment") else -entry.quantity
            net += delta
        item.opening_stock = item.current_stock - net
        item.save(update_fields=["opening_stock"])


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_reservation_no_active_overlap'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='opening_stock',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.RunPython(establish_opening_stock, migrations.RunPython.noop),
        migrations.AddField(
            model_name='order',
            name='idempotency_fingerprint',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
