# Generated by Django 6.0.3 on 2026-07-20 22:11

import django.db.models.deletion
from django.db import migrations, models


def backfill_payment_purpose(apps, schema_editor):
    PaymentAttempt = apps.get_model("hotel", "PaymentAttempt")
    PaymentAttempt.objects.filter(reservation_id__isnull=False).update(purpose="reservation_deposit")
    PaymentAttempt.objects.filter(idempotency_key__icontains="checkin").update(purpose="checkin")
    PaymentAttempt.objects.filter(idempotency_key__icontains="checkout").update(purpose="checkout")


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0024_inventoryitem_opening_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='accounting_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempt', to='hotel.journalentry'),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='last_reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='purpose',
            field=models.CharField(choices=[('order', 'Order'), ('reservation_deposit', 'Reservation Deposit'), ('checkin', 'Check-In'), ('checkout', 'Checkout')], default='order', max_length=30),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='reconciliation_status',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.RunPython(backfill_payment_purpose, migrations.RunPython.noop),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='chapa', max_length=30)),
                ('event_ref', models.CharField(max_length=160)),
                ('tx_ref', models.CharField(blank=True, default='', max_length=120)),
                ('payload_hash', models.CharField(max_length=64)),
                ('signature_valid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='received', max_length=20)),
                ('safe_summary', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=80)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='hotel.paymentattempt')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'status', 'received_at'], name='webhook_provider_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_ref'), name='unique_provider_webhook_event')],
            },
        ),
    ]
