# Generated by Django 6.0.3 on 2026-07-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_paymentattempt_accounting_entry_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentattempt',
            name='payment_attempt_amount_nonnegative',
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('expected_amount__gt', 0)), name='payment_attempt_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['created', 'initiated', 'verified', 'failed'])), name='payment_attempt_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('purpose__in', ['order', 'reservation_deposit', 'checkin', 'checkout'])), name='payment_attempt_purpose_valid'),
        ),
        migrations.AddConstraint(
            model_name='paymentwebhookevent',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['received', 'processed', 'rejected', 'failed'])), name='webhook_event_status_valid'),
        ),
    ]
