# Generated by Django 6.0.3 on 2026-07-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0027_auditevent'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='foliocharge',
            index=models.Index(fields=['added_at'], name='folio_added_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', 'updated_at'], name='ord_pay_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['waiter_id_ref', 'payment_status', 'updated_at'], name='ord_wait_pay_upd_idx'),
        ),
        migrations.AddIndex(
            model_name='roomhistory',
            index=models.Index(fields=['event_type', 'created_at'], name='rhist_event_created_idx'),
        ),
    ]
