# Generated by Django 6.0.2 on 2026-07-23 22:04

import core.storage
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0028_foliocharge_folio_added_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.storage.secure_category_image_path, validators=[core.validators.validate_file_signature, core.validators.validate_upload_size]),
        ),
        migrations.AlterField(
            model_name='guestprofile',
            name='id_scan',
            field=models.ImageField(blank=True, null=True, storage=core.storage.PrivateFileSystemStorage(), upload_to=core.storage.secure_private_guest_id_path, validators=[core.validators.validate_file_signature, core.validators.validate_upload_size]),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.storage.secure_menu_item_image_path, validators=[core.validators.validate_file_signature, core.validators.validate_upload_size]),
        ),
        migrations.AlterField(
            model_name='room',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=core.storage.secure_room_image_path, validators=[core.validators.validate_file_signature, core.validators.validate_upload_size]),
        ),
        migrations.AlterField(
            model_name='room',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=core.storage.secure_room_image_path, validators=[core.validators.validate_file_signature, core.validators.validate_upload_size]),
        ),
        migrations.AlterField(
            model_name='room',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.storage.secure_room_image_path, validators=[core.validators.validate_file_signature, core.validators.validate_upload_size]),
        ),
    ]
