# Generated by Django 6.0.2 on 2026-09-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0030_api_cache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='enabled_features',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='module_finance',
            field=models.BooleanField(default=True, verbose_name='Enable Finance & Accounting'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='module_inventory',
            field=models.BooleanField(default=True, verbose_name='Enable Inventory & Stock Control'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='module_pos',
            field=models.BooleanField(default=True, verbose_name='Enable Restaurant POS & Kitchen/Bar'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='module_rooms',
            field=models.BooleanField(default=True, verbose_name='Enable Rooms & Reservations'),
        ),
    ]
