# Generated by Django 6.0.2 on 2026-09-28 22:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0031_remove_systemsettings_enabled_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Cleaning', 'Cleaning'), ('Dirty', 'Dirty'), ('Inspected', 'Inspected'), ('Maintenance', 'Maintenance'), ('Reserved', 'Reserved')], default='Available', max_length=20),
        ),
        migrations.CreateModel(
            name='HousekeepingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('checkout_cleaning', 'Checkout Cleaning'), ('stayover_cleaning', 'Stayover / Daily Cleaning'), ('deep_cleaning', 'Deep Cleaning'), ('touch_up', 'Touch Up / Inspection'), ('turndown', 'Turn-Down Service')], default='stayover_cleaning', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent (Incoming Guest)')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('cleaned', 'Cleaned (Awaiting Inspection)'), ('inspected', 'Inspected & Approved'), ('failed', 'Inspection Failed / Re-clean')], default='pending', max_length=20)),
                ('assigned_to_username', models.CharField(blank=True, default='', max_length=150)),
                ('assigned_by_username', models.CharField(blank=True, default='', max_length=150)),
                ('notes', models.TextField(blank=True, default='')),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('inspected_by_username', models.CharField(blank=True, default='', max_length=150)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('inspection_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_tasks', to='hotel.room')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['room', 'status'], name='hk_room_status_idx'), models.Index(fields=['status'], name='hk_status_idx'), models.Index(fields=['assigned_to_username'], name='hk_assigned_idx')],
            },
        ),
        migrations.CreateModel(
            name='LostAndFoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('location_found', models.CharField(blank=True, default='', max_length=200)),
                ('found_by_name', models.CharField(max_length=150)),
                ('found_date', models.DateField(default=django.utils.timezone.now)),
                ('guest_name', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('storage_location', models.CharField(default='Housekeeping Safe Locker', max_length=100)),
                ('status', models.CharField(choices=[('stored', 'In Safe Storage'), ('claimed', 'Claimed / Returned'), ('disposed', 'Disposed / Donated')], default='stored', max_length=20)),
                ('claimed_by', models.CharField(blank=True, default='', max_length=200)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('claimant_phone', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_and_found_items', to='hotel.room')),
            ],
            options={
                'ordering': ['-found_date', '-created_at'],
                'indexes': [models.Index(fields=['status'], name='lost_found_status_idx'), models.Index(fields=['room'], name='lost_found_room_idx')],
            },
        ),
        migrations.CreateModel(
            name='MinibarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_quantity', models.IntegerField(default=2, help_text='Standard stock count for this item in minibar')),
                ('current_quantity', models.IntegerField(default=2, help_text='Current stock count in minibar')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Charge price to guest', max_digits=10)),
                ('last_restocked_at', models.DateTimeField(auto_now=True)),
                ('last_checked_by', models.CharField(blank=True, default='', max_length=150)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minibar_items', to='hotel.inventoryitem')),
                ('room', models.ForeignKey(blank=True, help_text='Specific room, or blank for hotel-wide default standard template', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minibar_items', to='hotel.room')),
            ],
            options={
                'ordering': ['room', 'item__name'],
                'indexes': [models.Index(fields=['room'], name='minibar_room_idx')],
            },
        ),
    ]
